name: Fetch Liked Songs

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  push:
    branches:
      - main

jobs:
  fetch-liked-songs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests opencc

    - name: Fetch liked songs
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      run: |
        import requests
        import base64
        import json
        from opencc import OpenCC
        from datetime import datetime, timezone
        import os

        CLIENT_ID = os.getenv('SPOTIFY_CLIENT_ID')
        CLIENT_SECRET = os.getenv('SPOTIFY_CLIENT_SECRET')
        REFRESH_TOKEN = os.getenv('SPOTIFY_REFRESH_TOKEN')

        def get_access_token():
            headers = {
                'Authorization': 'Basic ' + base64.b64encode(f"{CLIENT_ID}:{CLIENT_SECRET}".encode()).decode()
            }
            data = {
                'grant_type': 'refresh_token',
                'refresh_token': REFRESH_TOKEN
            }
            response = requests.post('https://accounts.spotify.com/api/token', headers=headers, data=data)
            return response.json()['access_token']

        def fetch_liked_songs(access_token):
            url = 'https://api.spotify.com/v1/me/tracks?limit=50'
            headers = {
                'Authorization': f'Bearer {access_token}'
            }
            songs = []
            while url:
                response = requests.get(url, headers=headers)
                data = response.json()
                songs.extend(data['items'])
                url = data.get('next')
            return songs

        access_token = get_access_token()
        songs = fetch_liked_songs(access_token)

        simplified_songs = []
        cc = OpenCC('t2s')
        for item in songs:
            track = item['track']
            song_info = {
                'song_name': cc.convert(track['name']),
                'singer_name': cc.convert(', '.join([artist['name'] for artist in track['artists']])),
                'added_at': item['added_at']
            }
            simplified_songs.append(song_info)

        with open('liked_songs.json', 'w', encoding='utf-8') as f:
            json.dump(simplified_songs, f, ensure_ascii=False, indent=4)

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add liked_songs.json
        git commit -m 'Update liked_songs.json'
        git push
